# Regresión lineal en Python

### El paquete scikit-learn para regresión lineal y la selección de rasgos

In [5]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('../datasets/ads/Advertising.csv')

In [7]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [10]:
feature_cols = ['TV', 'Radio', 'Newspaper']

In [11]:
# Nombre de las columnas que en principio serán variables predictoras
X = data[feature_cols]
# Variable a predecir
Y = data['Sales']

In [15]:
estimator = SVR(kernel='linear')
# Se indica que se utilizarán dos variables y que se hará en un solo paso
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X, Y)

In [16]:
# Obtener la lista de variables seleccionadas
selector.support_

array([ True,  True, False])

In [18]:
# Las variables seleccionadas aparecen con ranking = 1, las subsiguientes se ordenan de manera decreciente
selector.ranking_

array([1, 1, 2])

In [19]:
# Regresión lineal automática de scikit learn
from sklearn.linear_model import LinearRegression

In [22]:
X_pred = X[['TV', 'Radio']]

In [23]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
# Intercepto
lm.intercept_

2.9210999124051362

In [30]:
# Coeficientes
lm.coef_

array([0.04575482, 0.18799423])

In [28]:
# Valor de R^2
lm.score(X_pred, Y)

0.8971942610828956